# Generated by Django 4.0.1 on 2022-01-31 08:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255, verbose_name='ФИО')),
                ('position', models.CharField(max_length=155, verbose_name='Должность')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('salary', models.CharField(max_length=20, verbose_name='Зарплата')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='childrens', to='tree_app.worker', verbose_name='Начальник')),
            ],
            options={
                'verbose_name': 'Сотрудник',
            },
        ),
    ]
